// Generated by https://quicktype.io

export interface Lesson {
    id:         number;
    title:      string;
    instructor: string[];
    image_link: string;
}

// Generated by https://quicktype.io

export interface LessonFull {
    id:           number;
    created_at:   string;
    title:        string;
    summary:      string;
    duration:     string;
    release_date: string;
    image_link:   string;
    video_link:   string;
    intensity:    number;
    difficulty:   number;
    instructor:   number[];
    discipline:   number[];
    skill:        number[];
}
