// Generated by https://quicktype.io

export interface Serie {
    id:         number;
    created_at: string;
    name:       string;
    summary:    string;
    image_link: string;
    video_link: string;
    intensity:  number;
    difficulty: number;
    instructor: number[];
    discipline: number[];
    skill:      number[];
}
